#!/usr/bin/env python3
"""Export public TSV files for NAR submission download package."""
import sqlite3, csv, os, datetime

conn = sqlite3.connect('F:/水生无脊椎动物数据库/crustacean_virus_core.db')
outdir = 'F:/水生无脊椎动物数据库/public_download'
os.makedirs(outdir, exist_ok=True)
ts = datetime.datetime.now().strftime('%Y-%m-%d')

EXPORTS = [
    ('virus_master.tsv', 'public_virus_master'),
    ('crustacean_hosts.tsv', 'public_crustacean_hosts'),
    ('viral_isolates.tsv', 'public_viral_isolates'),
    ('evidence_records.tsv', 'public_evidence_records'),
    ('ref_literatures.tsv', 'public_ref_literatures'),
]

stats = {}
for filename, view in EXPORTS:
    path = os.path.join(outdir, filename)
    rows = conn.execute(f"SELECT * FROM {view}").fetchall()
    cols = [c[1] for c in conn.execute(f"PRAGMA table_info(\"{view.replace('public_', '')}\")").fetchall()]

    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f, delimiter='\t')
        w.writerow(cols)
        for row in rows:
            w.writerow([str(v) if v is not None else '' for v in row])

    size_mb = os.path.getsize(path) / 1024 / 1024
    stats[filename] = (len(rows), size_mb)
    print(f"  {filename}: {len(rows):,} rows, {size_mb:.1f} MB")

# README
readme = f"""# AquaVir-KB Public Data Download
## NAR Database Issue Submission
## Export Date: {ts}

### Scope
AquaVir-KB is a comprehensive knowledge base for aquatic invertebrate viruses,
covering Arthropoda, Mollusca, Echinodermata, Cnidaria, Porifera, Annelida,
Nematoda, Platyhelminthes, and Rotifera.

### Files

| File | Records | Size |
|------|--------|------|
"""
for f, (cnt, size) in stats.items():
    readme += f"| {f} | {cnt:,} | {size:.1f} MB |\n"

readme += f"""
### Data Dictionary

**virus_master.tsv** — Core virus species table
- canonical_name: Standard virus name (ICTV-aligned)
- virus_family / virus_genus: Taxonomy
- genome_type: Nucleic acid type (ssRNA+/dsDNA/etc.)
- host_phylum: Associated host phylum
- discovery_context: How the virus was discovered

**crustacean_hosts.tsv** — Aquatic invertebrate host species
- scientific_name: Host binomial name
- phylum / class / taxon_order / taxon_family: Taxonomy
- habitat: marine / freshwater / brackish
- aquaculture_status: major / minor / wild_only

**viral_isolates.tsv** — Virus isolate/sequence records
- accession: GenBank accession number
- virus_name / taxon_family / taxon_genus: Taxonomy
- genome_length: Genome size in bp
- master_id: FK to virus_master

**evidence_records.tsv** — Structured literature evidence
- evidence_type: host_range / diagnosis / pathogenicity / mortality / etc.
- evidence_strength: high / medium / low
- claim: Core finding from the literature
- virus_master_id / host_id / reference_id: FKs
- source_pmid / source_doi: Traceability

**ref_literatures.tsv** — References
- pmid / doi: Identifiers
- title / authors / journal / year: Bibliographic metadata

### Evidence Strength Tiers

| Tier | Criteria | Count |
|------|----------|-------|
| high | Experimental infection, Koch's postulates, virus isolation | {conn.execute("SELECT COUNT(*) FROM public_evidence_records WHERE evidence_strength='high'").fetchone()[0]:,} |
| medium | RT-PCR, sequencing, histopathology, phylogenetic analysis | {conn.execute("SELECT COUNT(*) FROM public_evidence_records WHERE evidence_strength='medium'").fetchone()[0]:,} |
| low | Metagenomic co-occurrence, computational prediction | {conn.execute("SELECT COUNT(*) FROM public_evidence_records WHERE evidence_strength='low'").fetchone()[0]:,} |

### Citation
[To be added upon publication]

### License
[To be determined]

### Contact
[Author contact information]

---
Generated by AquaVir-KB export pipeline v1.0
"""

with open(os.path.join(outdir, 'README.md'), 'w', encoding='utf-8') as f:
    f.write(readme)

# Compute total package size
total_size = sum(os.path.getsize(os.path.join(outdir, f)) for f in os.listdir(outdir))
print(f"\nTotal package: {total_size/1024/1024:.1f} MB")
print(f"README.md written")
print(f"Output: {outdir}")
conn.close()
